language: cpp
compiler: gcc
os: linux
dist: bionic
addons:
  apt:
    packages:
      - g++-8

before_script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 50 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - mkdir build_debug
  - cd build_debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cd ..
  - mkdir build_release
  - cd build_release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cd ..

script:
  - cd build_debug
  - make
  - ./CppDiagHelper_TestParser iteration_02 ../test/02/list.txt
  - cd ..
  - cd build_release
  - make
  - ./CppDiagHelper_TestParser iteration_02 ../test/02/list.txt
  - cd ..
